### ISSUE TITLE
Add all relevant modules

### ISSUE THREAD

**Issue by jfy133** [nf-core/createtaxdb#9]
### Description of feature

Already existing:

- [x] diamond-makedb
- [x] kaiju-mkbwt
- [x] kaiju-mkfmi
- [x] krakenuniq_download
- [x] krakenuniq_build
- [x] malt-build 
- [x] ?metaphlan-makdb
- [x] ?motus-downloaddb
- [x] ganon-buildcustom
- [x] kmcp-compute
- [x] kmcp-index

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/createtaxdb/issues/10
- [ ] https://github.com/nf-core/createtaxdb/issues/11
- [ ] https://github.com/nf-core/createtaxdb/issues/12
- [ ] https://github.com/nf-core/createtaxdb/issues/13
```
